dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - git

script:
  - git clone https://github.com/tanakh/cmdline.git
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake . 
  - cmake --build . -- -j2 


